apiVersion: v1
kind: Service
metadata:
  name: yetkinlik-frontend-service
  namespace: yetkinlik-prod
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: yetkinlik-frontend
  ports:
    - name: http
      port: 3000
      targetPort: 3000